### ISSUE TITLE
ViewPager problem

### ISSUE THREAD

**Issue by kyze8439690** [ChenSiLiang/RotatePhotoView#2]
When rotate gesture trigger viewpager scroll, rotate will be intercepted, cause image stop at inpropriate degree.
Maybe reset degree when PhotoView receive ACTION_CANCEL?

**Comment by ChenSiLiang** [comment]
I've test the code as you said ,the bug is real.You are so considerable!Thanks
I think your solution would work, I'll fix it later.

**Comment by kyze8439690** [comment]
If pointer count is two(or more than two), maybe it should call requestDisallowInterceptTouchEvent(true)? Sometime rotate will be intercept into a viewpager scroll gesture.

**Comment by ChenSiLiang** [comment]
yes,it should add isRotate in interface and call requestDisallowInterceptTouchEvent(true) when rotating

**Comment by kyze8439690** [comment]
And I advice separating rotating from zooming, rotate and zoom at the same time is not needs of the user wants.

**Comment by ChenSiLiang** [comment]
aha...this advice is good too,but in my consideration,I hope there will be more freedom for gesture and have a feeling of controlling the picture.
maybe it should leave a switch for developer or user to decide the combination.
thx :)
