### ISSUE TITLE
Force Close

### ISSUE THREAD

**Issue by Hitexroid** [ChenSiLiang/RotatePhotoView#4]
When i use Listener

`photoView.setOnRotateListener(new PhotoViewAttacher.OnRotateListener() { 
            @Override
            public void onRotate(int degree) {
               BA.Log(String.valueOf(degree));
            }
        });`

returns this error !

> java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
>     at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
>     at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
>     at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1438)
>     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2109)

**Comment by ChenSiLiang** [comment]
that's weird, what is your Android Version. Let me check the code

**Comment by ChenSiLiang** [comment]
I think this will help [Issue in PhotoView](https://github.com/chrisbanes/PhotoView#issues-with-viewgroups).
Did you  use a `ViewPager`?

**Comment by Hitexroid** [comment]
hi , my android version is 6
i don't use any `ViewPager` .

without listener , in landscape mode ,when i want rotate picture , app will crash too

**Comment by ChenSiLiang** [comment]
did the crash happen in the demo? 
do you mind post your code and let me check where the problem is ?

**Comment by Hitexroid** [comment]
```
PhotoView photoView;
private PhotoViewAttacher mAttacher;
```

`photoView.setImageBitmap(bm);
mAttacher = new PhotoViewAttacher(photoView);
mAttacher.setRotatable(true);`

**Comment by ChenSiLiang** [comment]
ahh...I see, the `PhotoView` is just in a Simple layou like `FrameLayout` or others?

**Comment by Hitexroid** [comment]
i added `PhotoView` in `FrameLayout`

Double Tap for zoom is working very well
but when i want rotate the photo , `PhotoView` will crash

**Comment by ChenSiLiang** [comment]
i had ran monkey but it did not crash.
could you post the hole error stack?
it seems like happen in `DrawerLayout`
